general:
  build_dir: tests

dependencies:
  pre:
    - sudo pip install paramiko PyYAML jinja2 httplib2
    - sudo pip install ansible

machine:
  environment:
    PLAYBOOK: playbook.yml
  pre:
    - uname -a
    - cat /proc/version
  hosts:
    myapp.com: 127.0.0.1

test:
  pre:
    - sudo ln -s ansible-role-apache ../../mauricios.Varnish
    - ansible --version
  override:
    - ansible-playbook $PLAYBOOK --syntax-check
    - ansible-playbook $PLAYBOOK --connection=local
    - "ansible-playbook $PLAYBOOK --connection=local | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
    - "varnish -v"
    - "curl -I http://localhost:6081"
