---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - ln -s ansible-role-varnish ../mauricios.Varnish

install:
  - sudo apt-get install -y curl

  # Install Ansible.
  - sudo pip install -r build/requirements.txt

script:
  - tests/test.sh

notifications:
  email: false
