---
- name: Configuring Varnish service
  become: yes
  template:
    src: varnish.j2
    dest: "{{ varnish.conf_path }}"
  notify: restart varnish

- block:
    - name: Make sure the directory of the VCL exists
      become: yes
      file:
        path: "{{ varnish.default_dir }}"
        state: directory

    - name: Configuring VCL
      become: yes
      template:
        src: default.vcl.j2
        dest: "{{ varnish.default_dir }}/default.vcl"
      notify: reload varnish
  when: varnish.install_vcl

- name: Task for container provision
  block:
    - name: Create Docker entrypoint
      become: yes
      copy:
        src: docker-entrypoint
        dest: /usr/local/bin/docker-entrypoint
        mode: 0755
  when: ansible_connection == 'docker'
