---
- name: "Open port {{ varnish['port'] }} in SELinux"
  sudo: yes
  template: src=etc/sysconfig/iptables.j2 dest=/etc/sysconfig/iptables
  notify:
  - restart iptables
  when: ansible_os_family == 'RedHat'
