---
- name: Install libselinux-python
  sudo: yes
  yum:
    name: libselinux-python
    state: present

- name: Add the Varnish rpms repo to yum
  sudo: yes
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
    state: present
  with_items: varnish['rpms']

- name: Ensure Varnish is present using yum
  sudo: yes
  yum:
    name: varnish
    state: present
